

# see https://alacritty.org/config-alacritty.html

[window]
padding = {x= 10, y= 10}            # Default value
opacity = 0.9

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold =  { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }
size = 14.0